repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-yaml
  - id: debug-statements
  - id: check-ast

- repo: https://github.com/asottile/pyupgrade
  rev: v2.35.0
  hooks:
  - id: pyupgrade
    args: ['--py37-plus']

- repo: https://github.com/python/black
  rev: 22.6.0
  hooks:
  - id: black

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
  - id: isort
    additional_dependencies: [toml]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.961
  hooks:
  - id: mypy
