name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:  # to allow manual re-runs


jobs:
  linting:
    name: "Perform linting checks"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip poetry tox
          poetry install
      - name: "Run pre-commit -a"
        run: |
          poetry run pre-commit run -a

  tests:
    name: "Python ${{ matrix.python-version}} on ${{ matrix.os }}"
    needs: linting
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "pypy-3.7"]
        os: [ubuntu-latest]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip poetry
          poetry install
      - name: "Run tests"
        run: |
          poetry run pytest --cov eq3bt --cov-report xml
